spring:
  application:
    name: klage-file-api
  main:
    banner-mode: OFF
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
      file-size-threshold: 2MB

server:
  port: 7080
  error:
    whitelabel:
      enabled: false

#Token validation
no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
    accepted_audience: ${AZURE_APP_CLIENT_ID}

management:
  endpoint:
    health:
      show-details: always
  endpoints.web:
    exposure:
      include: info, health, metrics, prometheus
    base-path: "/internal"
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: false

GCS_BUCKET: klagefiles