buckets:
  - klagefiles-dev
envs:
  - name: GCS_BUCKET
    value: klagefiles-dev
  - name: JAVA_TOOL_OPTIONS
    value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
  - name: JAVA_OPTS
    value: "-Xms256m -Xmx2048m"

springProfile: dev